name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_publish:
    runs-on: ubuntu-latest
    env:
      version: v0.1.${{ github.run_number }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test Klaabu package
      run: make test

    - name: Build Klaabu for Linux
      run: make GOOS=linux GOARCH=amd64 VERSION=${{ env.version }} build

    - name: Build Klaabu for MacOS
      run: make GOOS=darwin GOARCH=amd64 VERSION=${{ env.version }} build

    - name: Publish the Klaabu binary
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/master'
      with:
        tag_name: ${{ env.version }}
        files: |
          ./build/bin/klaabu-linux-amd64
          ./build/bin/klaabu-darwin-amd64
          ./build/klaabu-linux-amd64.sha512
          ./build/klaabu-darwin-amd64.sha512
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
